version: '3.7'

services:

  app:
    build: .
    restart: always
    ports:
      - "2015:2015"
    volumes:
      - ./srv/app-data:/srv/webtrees/data
    depends_on:
      - db

  db:
    image: mariadb:10.4
    restart: always
    volumes:
      - ./srv/db:/var/lib/mysql
    secrets:
      - db_root_password
      - db_name
      - db_user
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password

networks:
  default:
    name: webtrees_network

secrets:
  db_root_password:
    file: ./secrets/db_root_password
  db_name:
    file: ./secrets/db_name
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
