version: '3.7'

services:

  app:
    build: .
    restart: always
    ports:
      - "2015:2015"
    volumes:
      - appdata:/srv/webtrees/data
    networks:
      - frontend
      - backend
    depends_on:
      - db

  db:
    image: mariadb:10.4
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend
    env_file:
      - ./secrets/mariadb.env

networks:
  frontend:
  backend:

volumes:
  appdata:
  dbdata:
